Fix build on macOS
gstreamer-plugins-base-1.0 is a special dependency.
On macOS using Homebrew, it needs to be explicitly
added as dependency so that the includes will be
found. Otherwise it will fail with:

../gst/moodbar/gstfastspectrum.h:36:10: fatal error: 'gst/audio/gstaudiofilter.h' file not found